// F1.31 — public digital download endpoint.
//
//   GET /v1/orders/:orderId/downloads/:downloadToken
//
// The download token IS the authorization — the route is intentionally
// anonymous-allowed. The token is a 32-byte base64url string generated by the
// fulfillment worker and emailed to the buyer. Reused within the expiry
// window (same URL works multiple times); a separate access audit row is
// written on every hit so suspicious patterns can be investigated.
//
// Response: 302 redirect to a 5-minute signed S3 URL for the zip object.
//
// Status codes:
//   302  valid token, redirect to signed URL
//   404  unknown token / order mismatch / no fulfillment
//   410  token expired or fulfillment not in 'completed' state

import { GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import type { DbClient } from '@pkg/db';
import { schema } from '@pkg/db';
import { and, eq } from 'drizzle-orm';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';

import { hashIp, writeAudit } from '../lib/audit.js';
import { db as defaultDb } from '../lib/db.js';
import { buckets, s3 } from '../lib/storage.js';

const { fulfillments } = schema.commerce;

const SIGNED_URL_TTL_SECONDS = 5 * 60;

const paramsSchema = z.object({
  orderId: z.string().uuid(),
  downloadToken: z.string().min(20).max(200),
});

const getClientIp = (request: FastifyRequest): string | undefined => {
  const fwd = request.headers['x-forwarded-for'];
  if (typeof fwd === 'string' && fwd.length > 0) {
    return fwd.split(',')[0]?.trim();
  }
  return request.ip;
};

export interface DownloadsRoutesOptions {
  db?: DbClient;
  // Override the bucket and S3 client for tests.
  bucket?: string;
  signObject?: (key: string) => Promise<string>;
  now?: () => Date;
}

const downloadsRoutes = async (
  app: FastifyInstance,
  opts: DownloadsRoutesOptions = {},
): Promise<void> => {
  const db = opts.db ?? defaultDb;
  const bucket = opts.bucket ?? buckets.derivatives;
  const signObject =
    opts.signObject ??
    ((key: string) =>
      getSignedUrl(s3, new GetObjectCommand({ Bucket: bucket, Key: key }), {
        expiresIn: SIGNED_URL_TTL_SECONDS,
      }));
  const now = opts.now ?? (() => new Date());

  app.get('/v1/orders/:orderId/downloads/:downloadToken', async (request, reply) => {
    const parsed = paramsSchema.safeParse(request.params);
    if (!parsed.success) {
      return reply.code(404).send({ error: 'not found' });
    }
    const { orderId, downloadToken } = parsed.data;

    const rows = await db
      .select({
        id: fulfillments.id,
        orderId: fulfillments.orderId,
        status: fulfillments.status,
        downloadToken: fulfillments.downloadToken,
        downloadExpiresAt: fulfillments.downloadExpiresAt,
        payload: fulfillments.payloadJsonb,
      })
      .from(fulfillments)
      .where(and(eq(fulfillments.orderId, orderId), eq(fulfillments.downloadToken, downloadToken)))
      .limit(1);

    const row = rows[0];
    if (!row) {
      return reply.code(404).send({ error: 'not found' });
    }

    const expiresAt = row.downloadExpiresAt;
    const expired = !expiresAt || expiresAt.getTime() <= now().getTime();
    if (row.status !== 'completed' || expired) {
      // 410 Gone communicates a previously valid resource that is no longer.
      const ipHash = hashIp(getClientIp(request));
      await writeAudit(db, {
        action: 'fulfillment.digital.accessed',
        actorKind: 'user',
        targetKind: 'fulfillment',
        targetId: row.id,
        ipHash,
        userAgent:
          typeof request.headers['user-agent'] === 'string'
            ? request.headers['user-agent']
            : undefined,
        payload: { orderId, result: expired ? 'expired' : 'not_ready', status: row.status },
      });
      return reply.code(410).send({ error: 'download expired' });
    }

    const payload = (row.payload as { bundleKey?: string } | null | undefined) ?? undefined;
    const bundleKey = payload?.bundleKey ?? `bundles/${orderId}/${downloadToken}.zip`;

    let signedUrl: string;
    try {
      signedUrl = await signObject(bundleKey);
    } catch (err) {
      request.log.error({ err, bundleKey }, 'failed to sign download url');
      return reply.code(500).send({ error: 'internal error' });
    }

    const ipHash = hashIp(getClientIp(request));
    await writeAudit(db, {
      action: 'fulfillment.digital.accessed',
      actorKind: 'user',
      targetKind: 'fulfillment',
      targetId: row.id,
      ipHash,
      userAgent:
        typeof request.headers['user-agent'] === 'string'
          ? request.headers['user-agent']
          : undefined,
      payload: { orderId, result: 'ok', bundleKey },
    });

    return reply.code(302).redirect(signedUrl);
  });
};

export default downloadsRoutes;
